version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Asia/Tokyo"
    assignees:
      - 5ebec
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Asia/Tokyo"
    assignees:
      - 5ebec
