version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "05:00"
      timezone: "Asia/Tokyo"
    assignees:
      - h3y6e
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "05:00"
      timezone: "Asia/Tokyo"
    assignees:
      - h3y6e
