ci:
  collect:
    startServerCommand: yarn start
    url: http://localhost:9000/
  assert:
    preset: lighthouse:recommended
    assertions:
      unused-javascript: warn
      color-contrast: warn
      non-composited-animations: warn
      unminified-css: warn
      unused-css-rules: warn
      uses-responsive-images: warn
      csp-xss: warn
      crawlable-anchors: warn
      lcp-lazy-loaded: warn
  upload:
    target: temporary-public-storage
