- title: Email
  link: mailto:hash@5ebec.dev
  color: "#ea4335"
  icon:
    - fas
    - envelope

- title: Instagram
  link: https://www.instagram.com/5ebec/
  color: "#c13584"
  icon:
    - fab
    - instagram

- title: Twitter
  link: https://twitter.com/5ebec
  color: "#1da1f2"
  icon:
    - fab
    - twitter

- title: GitHub
  link: https://github.com/5ebec
  color: "#333"
  icon:
    - fab
    - github

- title: Amazon
  link: https://wishlist.5ebec.dev
  color: "#ff9900"
  icon:
    - fab
    - amazon

- title: Blog
  link: https://blog.5ebec.dev
  color: "#007e66"
  icon:
    - fas
    - pen-nib
