- title: Email
  link: mailto:while.soaks0d@icloud.com
  color: "#ea4335"
  icon:
    - fas
    - envelope

- title: Instagram
  link: https://www.instagram.com/h3y6e/
  color: "#c13584"
  icon:
    - fab
    - instagram

- title: Twitter
  link: https://x.com/h3y6e
  color: "#1da1f2"
  icon:
    - fas
    - x

- title: ActivityPub
  link: https://social.camph.net/@h3y6e
  color: "#99C203"
  icon:
    - fas
    - circle-nodes

- title: GitHub
  link: https://github.com/h3y6e
  color: "#333"
  icon:
    - fab
    - github

- title: Blog
  link: https://blog.h3y6e.com
  color: "#007e66"
  icon:
    - fas
    - pen-nib

- title: Wishlist
  link: https://wishlist.heyh.ooo
  color: "#ff9900"
  icon:
    - fab
    - amazon
