- category: langs
  contents:
    - C
    - C#
    - Python
    - Go
    - Java
    - Julia
    - JavaScript
    - Kotlin
    - TypeScript
    - HTML + CSS
    - Swift
    - LabVIEW
    - Whitespace

- category: tools
  contents:
    - GitHub
    - Google Cloud
    - AWS
    - Docker
    - Terraform
    - Unity
    - Hololens
    - Keyboards
