name: Lighthouse CI

on:
  - pull_request
  - pull_request_target

permissions:
  contents: read

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request_target' }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          # Check out the pull request HEAD
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-optional

      - name: Run Lighthouse CI
        run: yarn lh
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
