name: Visual Regression Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  pull_request_target:
    branches: [master]

permissions:
  contents: read

jobs:
  start-server-and-test:
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event_name != 'pull_request_target' }}

      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          # Check out the pull request HEAD
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Start server and test
        run: yarn vrt:start
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
